### ISSUE TITLE
Import custom model into dolphin game

### ISSUE THREAD

**Issue by BARULICK** [MoArtis/ResidentEvilSeamlessHdProject#164]
Hello
Remove my post after, cause it could be kind of unrelated.

I have skills in 3D modeling, and I really like your texture mode. So, is it possbile to hook up altered models into dolphin emulated game? I can work on Resident Evil models to add some resonable details, not just swap model to RE2 remake. Although I'm not sure what will happen to the RIG.

**To be short, I can remaster Re models for your mod.**

**Comment by Kayael76** [comment]
Hello Barulick, 

Thanks for your message ! To my knowledge, patching the iso would be the only way possible. Now Gamecube iso are pretty finicky because you can't exceed a certain size in octets (usually 1 459 978 240 octets), or if you don't reach it, you have to fill the remaining space with empty data. 

There are tools that allow extraction and rebuild of a GC iso like GCRebuilder (seems to be the best) so you might wanna start there. I don't guarantee it can work simply like that though, it wouldn't surprise me if some files were compressed to a specific GC format.

**Comment by BARULICK** [comment]
Hello, I only have will to work on the model, 
don't wanna dig all that complicated stuff I don't understand. So...
my regards

**Comment by Kayael76** [comment]
Best regards to you !
