### ISSUE TITLE
How can i solve this ?

### ISSUE THREAD

**Issue by Lottius** [MoArtis/ResidentEvilSeamlessHdProject#181]
![Sem título](https://user-images.githubusercontent.com/62947027/78036386-9ef24480-7340-11ea-92f4-020733922bd4.png)

**Comment by Kayael76** [comment]
Hi, 

It looks like a texture cache accuracy issue. Can you check in Dolphin under Graphics > Hacks if the Texture Cache is greyed out ? If not, move the slider to the Safe position. 

Otherwise, with dolphin closed, open User\Config\GFX.ini, look for SafeTextureCacheColorSamples and set it to 640. After that you should be able to use the slider. 

Restart Dolphin and see if it fixed the issue.

**Comment by Lottius** [comment]
My dolphin already have this config, don't you have another solution, please ?

**Comment by Kayael76** [comment]
But is it greyed out ? If that's the case, you might see the cursor on safe but it's not, it's using a custom value that you must set to 640 to move the slider and put it to safe.

**Comment by Lottius** [comment]
Is not greyed

**Comment by Kayael76** [comment]
Ok so that's weird because it should be, you're using our custom Dolphin and using the RE3 build, right ? Not the one from RE2 or any other versions of Dolphin ?

**Comment by Lottius** [comment]
Yes, I even downloaded the emulator again from the website

**Comment by Kayael76** [comment]
That's weird, you can eventually delete the contents of the User/Cache/Shaders folder and try another video backend in Graphics > General but I don't really know what's going on tbh.
