### ISSUE TITLE
RE2 Shadow issue , and reset settings ? 

### ISSUE THREAD

**Issue by sssal77** [MoArtis/ResidentEvilSeamlessHdProject#189]
Hello is this game fully playable from start to end ?
also i notes the shadow didn't exactly set under player ,  How to fix that ?

and finally How do i  reset Graphics settings in case if i mess with it ?

**Comment by MoArtis** [comment]
@sssal77 Hello! You are not supposed to mess with the graphic settings. The packs come with a pre-configured and hacked version of Dolphin specifically prepared for our mods.
If the shadows don't match, it's probably because you changed the aspect ratio to 16:9 and activate the 16:9 hack. Classic RE games are mostly 2d games created with a 4:3 aspect ratio in mind. Forcing another ratio will break them in some ways.

**Comment by MoArtis** [comment]
If you want to get back to the original settings, you have to copy the gfx.ini file in the downloaded pack located in the folder "User/Config" and paste it to your corresponding local folder.
