### ISSUE TITLE
Seam on the right side of the equipped weapon

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#65]
![image](https://user-images.githubusercontent.com/3904610/56543633-95932080-65a4-11e9-9a27-e0f366291fb7.png)

Is there a way to avoid that seam on the left side of the equipped weapon?

![image](https://user-images.githubusercontent.com/3904610/56543790-1520ef80-65a5-11e9-8070-c2c1083c7c63.png)

**Comment by Kayael76** [comment]
Good eyes ! I'm on TV so I never noticed it. Yes I can fix this, I know why it does that.

**Comment by Kayael76** [comment]
I created a 1.1 update folder, I put a fix for this. I you squint enough, you may still see a slight seam, because the bacground of the Equip slot is an empty double-sized slot, and the actual 1 slot weapon is just copy/pasted in the middle of it. Since the gradient I made is way more subtle than the original, it still a bit viewable. I could redo the whole sheet from scratch someday.

![GHAE08-49](https://user-images.githubusercontent.com/48800201/57151024-2bfae980-6dd0-11e9-8c7c-2c66b325b4aa.png)

**Comment by MoArtis** [comment]
Seems good enough to me. 👍

**Comment by Kayael76** [comment]
Working as intended !
