### ISSUE TITLE
Controller vibration is not working on Dolphin

### ISSUE THREAD

**Issue by MoArtis** [MoArtis/ResidentEvilSeamlessHdProject#69]
Someone on youtube told me that the controller vibration on dolphin is not working.

I remember facing the same problem with my Xbox one controller a couple of weeks ago. I will have to look into that.

@Kayael76 @saeedalshaikhpygas Is it working on your side?

**Comment by Kayael76** [comment]
Never had much trouble, I'm using a X360 controller; usually trouble happens if you plug the controller after launching Dolphin, but restarting the emulator fixes it. 
You need to check if in the Controller panel, you have Motor R|Motor L in the Rumble sidebar.

Other than that, I don't see why it wouldn't work.

**Comment by MoArtis** [comment]
Btw, my problem and that other person problem was related to that option in the controller menu. It was set to 0. 🙂

![image](https://user-images.githubusercontent.com/3904610/57505823-6c0c2000-732c-11e9-99c1-67a3446fb7b8.png)

**Comment by manaboy** [comment]
Still not working for me

**Comment by MoArtis** [comment]
@manaboy You know it's not super helpful to just say something is not working. :D Please give us more info. 
What is your controller? What have you tried so far?

**Comment by manaboy** [comment]
So sorry about that, I've tried the Xbox 360 controller with Microsoft Xbox 360 wireless adaptor for Windows, and the rumble didn't work, I then got myself Ds4windows and connected my official PS4 controller via Bluetooth and that also didn't work, works on other yuzu and cemu no problem. I think the issue is what this user said on his last post https://forums.dolphin-emu.org/Thread-xbox-one-controller-rumble-not-working

**Comment by MoArtis** [comment]
What does that value says (after selecting your controller on that topdown device list):
![image](https://user-images.githubusercontent.com/3904610/107976744-01097600-6ff5-11eb-8f92-1a824bdcc8f5.png)

**Comment by manaboy** [comment]
Hi thanks for the reply, it says 'Motor L' | 'Motor R' and the value on the range is 100 still not working :(

**Comment by Quickshadoww** [comment]
working on windows, but not on mac.
