### ISSUE TITLE
AMS needed for ROOM_20F_07, 20F_08, 204_08 and 204_09

### ISSUE THREAD

**Issue by Kayael76** [MoArtis/ResidentEvilSeamlessHdProject#88]
From ythealien on DIscord :  

"while I was coming back from the basement with the club key
when you use the shutter cable on the east hallway just by the basement entrance
it plays the little video of the shutters closing
but the cable is still cut in the angle used for the video, for some reason"

The same situation can occur in the East corridor (204_08 and 204_09)

Taking a quick look at the BG and the masks, it's an AMS case.

**Comment by Kayael76** [comment]
I added the upscaled versions and the missing GC dump in Room 20F & 204 AMS in the 1.1 update folder.

**Comment by MoArtis** [comment]
I'm actually missing all the GC dumps or 204_09 too. 🤔

**Comment by MoArtis** [comment]
Ok I'm done editing the data of the mixed AMS cases and I matched the missing textures manually. Very strange that the data were "lost". Since the full pack had these textures.
Anyway, the new textures are ready and can be found in a new shared folder where we will prepare the update pack. (I also updated the full pack folder)

**Comment by Kayael76** [comment]
Alright, RE2 still had a few surprises left it seems haha xD

**Comment by Kayael76** [comment]
Working as intended !
